### ISSUE TITLE
Colocar link do projeto no README.md

### ISSUE THREAD

**Issue by mary-programms** [joaodiazz/amazing-graph#1]
Alo João!

Caso tenhas o projeto no Pages do GitHub, no teu README.md coloca esse link para conseguirmos ver logo o website do nosso lado, os screenshots são bons mas ver o site live é ainda melhor!

Basta colares isto no teu README.md:
```<a href="o_link_do_projeto" target="_blank">nome_do_projeto</a>```

Espero que ajude e qualquer coisa desculpa o incomodo! :)

**Comment by joaodiazz** [comment]
zero incomodo Mariana, muito obrigado pela ideia.

acabei de arrumar o que tinha que ser arrumado e adicionei o link para o website no README.md.
